#ifndef __CLOX2_CHUNK_H__
#define __CLOX2_CHUNK_H__

#include "clox/value.h"
#include "clox/valarray.h"

#define OPCODE_ENUM_LIST \
    ENUM_OPCODE_DEF(OP_ARRAY) \
    ENUM_OPCODE_DEF(OP_CONSTANT) \
    ENUM_OPCODE_DEF(OP_CONSTANT_ZERO) \
    ENUM_OPCODE_DEF(OP_CONSTANT_ONE) \
    ENUM_OPCODE_DEF(OP_CONSTANT_TWO) \
    ENUM_OPCODE_DEF(OP_NIL) \
    ENUM_OPCODE_DEF(OP_TRUE) \
    ENUM_OPCODE_DEF(OP_FALSE) \
    ENUM_OPCODE_DEF(OP_POP) \
    ENUM_OPCODE_DEF(OP_DUP) \
    ENUM_OPCODE_DEF(OP_GET_LOCAL) \
    ENUM_OPCODE_DEF(OP_SET_LOCAL) \
    ENUM_OPCODE_DEF(OP_GET_GLOBAL) \
    ENUM_OPCODE_DEF(OP_DEFINE_GLOBAL) \
    ENUM_OPCODE_DEF(OP_SET_GLOBAL) \
    ENUM_OPCODE_DEF(OP_GET_UPVALUE) \
    ENUM_OPCODE_DEF(OP_SET_UPVALUE) \
    ENUM_OPCODE_DEF(OP_STATIC_FIELD) \
    ENUM_OPCODE_DEF(OP_GET_PROPERTY) \
    ENUM_OPCODE_DEF(OP_SET_PROPERTY) \
    ENUM_OPCODE_DEF(OP_GET_INDEX) \
    ENUM_OPCODE_DEF(OP_SET_INDEX) \
    ENUM_OPCODE_DEF(OP_GET_SUPER) \
    ENUM_OPCODE_DEF(OP_EQUAL) \
    ENUM_OPCODE_DEF(OP_GREATER) \
    ENUM_OPCODE_DEF(OP_LESS) \
    ENUM_OPCODE_DEF(OP_ADD) \
    ENUM_OPCODE_DEF(OP_SUBTRACT) \
    ENUM_OPCODE_DEF(OP_MULTIPLY) \
    ENUM_OPCODE_DEF(OP_DIVIDE) \
    ENUM_OPCODE_DEF(OP_MODULUS) \
    ENUM_OPCODE_DEF(OP_EXPONENT) \
    ENUM_OPCODE_DEF(OP_NOT) \
    ENUM_OPCODE_DEF(OP_NEGATE) \
    ENUM_OPCODE_DEF(OP_PRINT) \
    ENUM_OPCODE_DEF(OP_JUMP) \
    ENUM_OPCODE_DEF(OP_JUMP_IF_FALSE) \
    ENUM_OPCODE_DEF(OP_LOOP) \
    ENUM_OPCODE_DEF(OP_CALL) \
    ENUM_OPCODE_DEF(OP_INVOKE) \
    ENUM_OPCODE_DEF(OP_SUPER_INVOKE) \
    ENUM_OPCODE_DEF(OP_CLOSURE) \
    ENUM_OPCODE_DEF(OP_CLOSE_UPVALUE) \
    ENUM_OPCODE_DEF(OP_RETURN) \
    ENUM_OPCODE_DEF(OP_CLASS) \
    ENUM_OPCODE_DEF(OP_INHERIT) \
    ENUM_OPCODE_DEF(OP_METHOD) \
    ENUM_OPCODE_DEF(OP_STATIC_METHOD) \
    ENUM_OPCODE_DEF(OP_THROW) \
    ENUM_OPCODE_DEF(OP_PUSH_EXCEPTION_HANDLER) \
    ENUM_OPCODE_DEF(OP_POP_EXCEPTION_HANDLER) \
    ENUM_OPCODE_DEF(OP_PROPAGATE_EXCEPTION)

typedef enum {
#define ENUM_OPCODE_DEF(name) name,
    OPCODE_ENUM_LIST
#undef ENUM_OPCODE_DEF
    OP_LAST
} OpCode;

static_assert(
    OP_CONSTANT_ZERO + 1 == OP_CONSTANT_ONE &&
    OP_CONSTANT_ZERO + 2 == OP_CONSTANT_TWO,
    "Constant instructions must be consecutive."
);

typedef struct {
    int offset;
    int line;
} LineStart;

typedef struct {
    int count;
    int capacity;
    uint8_t* code;

    ValueArray constants;

    int lineCount;
    int lineCapacity;
    LineStart* lines;
} Chunk;

void initChunk(Chunk* chunk);

void freeChunk(Chunk* chunk);

void writeChunk(Chunk* chunk, uint8_t byte, int line);

int getLine(Chunk* chunk, int instruction);

int addConstant(Chunk* chunk, Value value);

#endif //__CLOX2_CHUNK_H__
