#ifndef __CLOX2_EXITCODE__
#define __CLOX2_EXITCODE__

#define EXIT_CODE_BAD_ARGS 30

#define EXIT_CODE_COMPILE_ERROR 60
#define EXIT_CODE_RUNTIME_ERROR 70

#define EXIT_CODE_FAILED_TO_READ_FILE 91
#define EXIT_CODE_FAILED_TO_OPEN_FILE 92

#endif // __CLOX2_EXITCODE__
