#ifndef __CLOX2_TOKEN_H__
#define __CLOX2_TOKEN_H__

typedef enum {
	// Single character tokens
	TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN, TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET, 
	TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE, TOKEN_COMMA, TOKEN_COLON, 
	TOKEN_DOT, TOKEN_VERTICAL_LINE, TOKEN_MINUS, TOKEN_PERCENT, 
	TOKEN_PLUS, TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR, 
	TOKEN_QUESTION, TOKEN_BANG, TOKEN_EQUAL, TOKEN_GREATER, 
	TOKEN_LESS,

	// Two character tokens
	TOKEN_MINUS_EQUAL, TOKEN_PERCENT_EQUAL, TOKEN_PLUS_EQUAL, TOKEN_SLASH_EQUAL, 
	TOKEN_STAR_EQUAL, TOKEN_STAR_STAR, TOKEN_BANG_EQUAL, TOKEN_EQUAL_EQUAL, 
	TOKEN_GREATER_EQUAL, TOKEN_LESS_EQUAL,

	// Value literal tokens
	TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

	// Keyword tokens
	TOKEN_AND, TOKEN_AS, TOKEN_BREAK, TOKEN_CASE, 
	TOKEN_CATCH, TOKEN_CLASS, TOKEN_CONTINUE, TOKEN_DEFAULT, 
	TOKEN_ELSE, TOKEN_FALSE, TOKEN_FOR, TOKEN_FUN, 
	TOKEN_FINALLY, TOKEN_IF, TOKEN_NIL, TOKEN_OR, 
	TOKEN_PRINT, TOKEN_RETURN, TOKEN_STATIC, TOKEN_SUPER, 
	TOKEN_SWITCH, TOKEN_THIS, TOKEN_THROW, TOKEN_TRUE, 
	TOKEN_TRY, TOKEN_VAR, TOKEN_WHILE,

	// Special tokens
	TOKEN_ERROR, TOKEN_EOF
} TokenType;

typedef struct {
	int line;
	int column;
} TokenLocation;

typedef struct {
	TokenLocation loc;
    TokenType type;
	int length;
	const char* start;
} Token;

#endif // __CLOX2_TOKEN_H__
