#ifndef __CLOX2_EXITCODE__
#define __CLOX2_EXITCODE__

#define EXIT_CODE_BAD_ARGS 34
#define EXIT_CODE_FAILED_TO_READ_FILE 74
#define EXIT_CODE_COMPILE_ERROR 65
#define EXIT_CODE_RUNTIME_ERROR 70

#endif // __CLOX2_EXITCODE__
